network.host: 0.0.0.0
path:
  data: /usr/share/elasticsearch/data
  logs: /data/logs/elasticsearch

# node.name:    ${HOSTNAME}
node.name:   mynode
cluster.name: dev-local

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.zen.minimum_master_nodes: 1

# index.analysis.analyzer.default.type: ik
